vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: /images/ile-de-la-reunion
            upload_destination: '%kernel.project_dir%/public/images/ile-de-la-reunion'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
