easy_admin:

    site_name: 'Administration'

    design:
        assets:
            css:
                - '//cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.9/css/mdb.min.css'
                - '/assets/css/easy-admin.css'
            js:
                - '//cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js'
                - '//cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.9/js/mdb.min.js'

        brand_color: '#fe5f5f'

        menu:
            - { label: 'Users' }
            - { entity: 'Admin', icon: 'user' }
            - { entity: 'Editor', icon: 'user' }
            - { label: 'Listings' }
            - { entity: 'Products', label: 'Produits', icon: 'tag' }
            - { entity: 'ProductCategory', label: 'Catégories', icon: 'tag' }
            - { label: 'Blog' }
            - { entity: 'Articles', label: 'Articles', icon: 'tag' }
            - { entity: 'Categories', label: 'Catégories', icon: 'tag' }
            - { entity: 'MotsCles', label: 'Mots Clés', icon: 'tag' }
            - { entity: 'Commentaires', label: 'Commentaires', icon: 'tag' }
            - { label: 'Options' }
            - { entity: 'HomeSlider', label: 'Slider Home', icon: 'tag' }